[theme]

# Primary accent for interactive elements
primaryColor = '#f4d35e'

# Background color for the main content area
backgroundColor = '#0d3b66'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#f4d35e'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"